### ISSUE TITLE
English version?

### ISSUE THREAD

**Issue by joadske** [ehorvat1/AmsToMqttBridge-EHo#1]
Hi, previously you had an English version, do you have any plans to make an english version as well?

**Comment by ehorvat1** [comment]
Hi, yes I will do an english Version. Should be ready by 9.9. Then there should be a firmware-en.bin for English and firmware-de.bin for German. I also have to document some new MQTT Items which were introduced lately. Since I "deforked" this repo I should also do releases...

**Comment by ehorvat1** [comment]
Hi, english Version now available at "english" branch. See:  https://github.com/ehorvat1/AmsToMqttBridge-EHo/tree/english

**Comment by joadske** [comment]
Thanks,

**Comment by ehorvat1** [comment]
No problem, I could do other Languages too....but would need the correct wording....Anyway one could use the browser integrated translation function (right click...translate to...) but I did see that this goes back to original when web page is changed. And I found the translation a bit "funny" for those tecnical terms, so I did a "nativ" german one.
